image: pytorch/pytorch:latest

variables:
  OSS_BUCKET: "ri-thudep-2025"
  OSS_REGION: "oss-cn-beijing"

score:
  script:
    - apt update && apt -y install make wget curl bash unzip
    - apt -y install python3-scipy
    - pip install nibabel tqdm
    
    - make all | tee log
    
    - |
      echo "Attempting to extract the final score..."
      # 使用 awk 提取最后一个“总得分”下面的数值，更稳健
      SCORE_VALUE=$(awk '/^总得分:$/ {getline; score=$0} END {print score}' log | tr -d '[:space:]')
      
      if [ -z "${SCORE_VALUE}" ]; then
        echo "ERROR: Could not extract the final score from the log file."
        cat log
        exit 1
      fi
      
      echo "Final score extracted: ${SCORE_VALUE}"
      
      TEAM_NAME=$(echo $CI_PROJECT_PATH | sed 's/radiation-imaging-contest\/competitor\///g' | sed 's/\/.*//g')
      TIMESTAMP=$(date --rfc-3339=seconds)
      
      JSON_PAYLOAD=$(printf '{"team": "%s", "score": %s, "time": "%s", "secret": "%s"}' \
        "${TEAM_NAME}" \
        "${SCORE_VALUE}" \
        "${TIMESTAMP}" \
        "${LEADERBOARD_SECRET}")

      echo "Submitting the following payload to the leaderboard:"
      echo "${JSON_PAYLOAD}"
      
      curl -f --location 'https://ri-leaderboard.thudep.com' \
        --header 'Content-Type: application/json' \
        --data "${JSON_PAYLOAD}"
      
      echo $TEAM_NAME > team_name

    - curl https://gosspublic.alicdn.com/ossutil/install.sh | bash
    - ossutil config -e "${OSS_REGION}.aliyuncs.com" -i "${OSS_ACCESS_KEY_ID}" -k "${OSS_ACCESS_KEY_SECRET}"

    - |
      if ! ossutil ls oss://${OSS_BUCKET}/${TEAM_NAME} | grep -q "${TEAM_NAME}"; then
        echo "Creating OSS directory: oss://${OSS_BUCKET}/${TEAM_NAME}/"
        ossutil mkdir oss://${OSS_BUCKET}/${TEAM_NAME}
      else
        echo "OSS directory already exists: oss://${OSS_BUCKET}/${TEAM_NAME}"
      fi

      FILE_NAME=unet-$(date +%s).pth
      echo $FILE_NAME > file_name
      mv unet.pth $FILE_NAME

      echo "Uploading ${FILE_NAME} to oss://${OSS_BUCKET}/${TEAM_NAME}/${FILE_NAME}"
      ossutil cp ./${FILE_NAME} oss://${OSS_BUCKET}/${TEAM_NAME}/${FILE_NAME}

  artifacts:
    paths:
      - ./file_name
      - ./team_name

create_release:
  image: gitlab/glab:latest
  needs:
    - job: score
  rules:
    - if: $CI_COMMIT_TAG 
      when: on_success
  script:
    - TEAM_NAME=$(cat team_name)
    - FILE_NAME=$(cat file_name)
    - |
      glab auth login --hostname $CI_SERVER_HOST --job-token $CI_JOB_TOKEN
      glab release create ${CI_COMMIT_TAG} --notes "模型下载链接：[${FILE_NAME}](https://${OSS_BUCKET}.${OSS_REGION}.aliyuncs.com/${TEAM_NAME}/${FILE_NAME})"