image: pytorch/pytorch:latest

variables:
  OSS_BUCKET: "ri-thudep-2025"
  OSS_REGION: "oss-cn-beijing"

score:
  script:
    - apt update && apt -y install make wget curl bash unzip
    - apt -y install python3-scipy
    - pip install nibabel tqdm
    
    - make all | tee log
    - |
      echo "Your score is $(grep -Pzo "总得分:\n\d+\.\d+" log | sed '1d')"
      TEAM_NAME=$(echo $CI_PROJECT_PATH | sed 's/radiation-imaging-contest\/competitor\///g' | sed 's/\/.*//g')
      curl --location 'https://ri-leaderboard.thudep.com' \
          --header 'Content-Type: application/json' \
          --data "{\"team\": \"$TEAM_NAME\",\"score\": $(grep -Pzo '总得分:\n\d+\.\d+' log | sed '1d'),\"time\": \"$(date --rfc-3339=seconds)\",\"secret\":\"${LEADERBOARD_SECRET}\"}"
      echo $TEAM_NAME > team_name

    - curl https://gosspublic.alicdn.com/ossutil/install.sh | bash
    - ossutil config -e "${OSS_REGION}.aliyuncs.com" -i "${OSS_ACCESS_KEY_ID}" -k "${OSS_ACCESS_KEY_SECRET}"
    - |
      if ! ossutil ls oss://${OSS_BUCKET}/${TEAM_NAME} | grep -q "${TEAM_NAME}"; then
        echo "Creating OSS directory: oss://${OSS_BUCKET}/${TEAM_NAME}/"
        ossutil mkdir oss://${OSS_BUCKET}/${TEAM_NAME}
      else
        echo "OSS directory already exists: oss://${OSS_BUCKET}/${TEAM_NAME}"
      fi

    - FILE_NAME=unet-$(date +%s).pth
    - echo $FILE_NAME > file_name
    - mv unet.pth $FILE_NAME

    - ossutil cp ./${FILE_NAME} oss://${OSS_BUCKET}/${TEAM_NAME}/${FILE_NAME}

  artifacts:
    paths:
      - ./file_name
      - ./team_name

create_release:
  image: gitlab/glab:latest
  needs:
    - job: score
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success

  script:
    - TEAM_NAME=$(cat team_name)
    - FILE_NAME=$(cat file_name)
    - |
      glab auth login --hostname $CI_SERVER_HOST --job-token $CI_JOB_TOKEN
      glab release create ${CI_COMMIT_TAG} --notes "下载链接：[${FILE_NAME}](https://${OSS_BUCKET}.${OSS_REGION}.aliyuncs.com/${TEAM_NAME}/${FILE_NAME})"

